//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProformaLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_PFL_RESOURCES_SS_V
    {
        public int SYSID { get; set; }
        public Nullable<int> SYS_PROJECT_ID { get; set; }
        public string FISCAL_YEAR { get; set; }
        public string BUSINESS { get; set; }
        public string BUSINESS_UNIT { get; set; }
        public string HIGH_ORG { get; set; }
        public string MID_ORG { get; set; }
        public string COMMENTS { get; set; }
        public string REQUIRED_SKILL { get; set; }
        public string TEAM { get; set; }
        public string FISCAL_MONTH { get; set; }
        public string TYPE { get; set; }
        public string WBS_NUMBER { get; set; }
        public string FISCAL_YEAR_MONTH { get; set; }
        public string VALUE { get; set; }
        public string PROJECT_NO { get; set; }
        public string PROJECT_NAME { get; set; }
        public string SYSTEM { get; set; }
        public string SOURCE_CREATED_BY { get; set; }
        public string SOURCE_CREATED_DT { get; set; }
        public string SOURCE_MODIFIED_BY { get; set; }
        public string SOURCE_MODIFIED_DT { get; set; }
        public string SNAPSHOT_DT { get; set; }
        public string MAKEDW_UPDATE_DT { get; set; }
    }
}
