//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProformaLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapitalInfo
    {
        public int MasterID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string Type { get; set; }
        public string WBSNumber { get; set; }
        public string Priority { get; set; }
        public string Impactofnotinvesting { get; set; }
        public string CapitalCategory { get; set; }
        public string CapitalType { get; set; }
        public string Description { get; set; }
        public Nullable<int> AOPProject { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> RowID { get; set; }
    }
}
