//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProformaLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectExpensesInfo_CJI3_Selection
    {
        public int Sysid { get; set; }
        public string FiscalYear { get; set; }
        public string Month { get; set; }
        public string PostingDate { get; set; }
        public string Object { get; set; }
        public string CO_Object_Name { get; set; }
        public string CostElementName { get; set; }
        public string PurchasingDocument { get; set; }
        public string PurchaseOrderText { get; set; }
        public string NameOfOffsettingaccount { get; set; }
        public Nullable<decimal> TotalQuantity { get; set; }
        public Nullable<decimal> Val_COAreaCrcy { get; set; }
        public string UserName { get; set; }
        public string DE_ExpenseCategory { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
