//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProformaLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Summary
    {
        public int Sysid { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> value { get; set; }
        public string Formula { get; set; }
        public string FormulaSource { get; set; }
        public string SubFormula { get; set; }
    }
}
