//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProformaLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_CJI3
    {
        public int Sysid { get; set; }
        public string FiscalYear { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public string Period { get; set; }
        public string Object { get; set; }
        public string CO_Object_Name { get; set; }
        public string Partner_CCtr { get; set; }
        public string CostElement { get; set; }
        public string CostElementName { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public string DocumentHeaderText { get; set; }
        public string PurchasingDocument { get; set; }
        public string PurchaseOrderText { get; set; }
        public string NameOfOffsettingaccount { get; set; }
        public Nullable<decimal> TotalQuantity { get; set; }
        public string PostedUnitOfMeas { get; set; }
        public string COAreaCurrency { get; set; }
        public Nullable<decimal> Val_COAreaCrcy { get; set; }
        public string UserName { get; set; }
        public string UnitOfMeasure { get; set; }
        public string Total_Quantity { get; set; }
        public string DocumentType { get; set; }
        public string DocumentNumber { get; set; }
        public Nullable<System.DateTime> Record_CreatedOn { get; set; }
    }
}
