//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProformaLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Snapshot_Config
    {
        public int Sysid { get; set; }
        public Nullable<int> FisYear { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string DataCount { get; set; }
        public string DataRefreshStatus { get; set; }
        public Nullable<System.DateTime> RefreshDate { get; set; }
    }
}
