//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProformaLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_SAP_PO_Data
    {
        public int Sysid { get; set; }
        public Nullable<System.DateTime> DebitDate { get; set; }
        public string ObjectType { get; set; }
        public string Object { get; set; }
        public string CostElement { get; set; }
        public Nullable<decimal> Val_COAreaCrcy { get; set; }
        public Nullable<decimal> TotalQuantity { get; set; }
        public string UnitOfMesure { get; set; }
        public string RefDocumentNumber { get; set; }
        public string ReferenceItem { get; set; }
        public string Vendor { get; set; }
        public string COObjectName { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public string FiscalYear { get; set; }
        public string Peroid { get; set; }
        public string MaterialGroup { get; set; }
        public string UserName { get; set; }
    }
}
