//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProformaLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_VendorList
    {
        public int Sysid { get; set; }
        public string Vendor { get; set; }
        public string NameOfVendor { get; set; }
        public string Street { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string AccountGroup { get; set; }
        public string SearchTerm { get; set; }
        public string CentralPurchasingBlock { get; set; }
        public string BlockFunction { get; set; }
        public string CentalDeletionFlag { get; set; }
        public string OneTimeAccount { get; set; }
        public string PurchOrgDescr { get; set; }
        public string TermOfPayment { get; set; }
        public string Incoterms { get; set; }
        public string PurchBlockForPurchasingOrganization { get; set; }
        public string DeleteFlagForPurchasingOrganization { get; set; }
        public string MinimumOrderValue { get; set; }
        public string OrderCurrency { get; set; }
        public string SalesPerson { get; set; }
        public string Telephone { get; set; }
        public string ReferencePurchasingOrg { get; set; }
        public string NumberOfPurchasingOrganizations { get; set; }
        public string Record_CreatedOn { get; set; }
        public string Record_CreatedBy { get; set; }
        public string Record_ModifiedOn { get; set; }
        public string Record_ModifiedBy { get; set; }
    }
}
