//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProformaLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_ProjectChargeBack
    {
        public int Sysid { get; set; }
        public string MidOrg { get; set; }
        public string Site { get; set; }
        public string ProjectCharging { get; set; }
    }
}
