//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProformaLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification_Log
    {
        public int Sysid { get; set; }
        public Nullable<int> NotificationID { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
