//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProformaLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDW_Resource_Master
    {
        public int Sysid { get; set; }
        public string PWD_ResourceName { get; set; }
        public string PWD_BusinessUnit { get; set; }
        public string PWD_HighOrg { get; set; }
        public string PWD_MidOrg { get; set; }
        public string PWD_Team { get; set; }
    }
}
