//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProformaLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFL_MDT_PDW
    {
        public int SYSID { get; set; }
        public string PROJECTKEY { get; set; }
        public string PROJECTNAME { get; set; }
        public string RESOURCENAME { get; set; }
        public string RESOURCEACTIVE { get; set; }
        public string ASSIGNEDUNASSIGNED { get; set; }
        public string RESOURCECATEGORY { get; set; }
        public string RESOURCEKEY { get; set; }
        public string SKILLNAME { get; set; }
        public string TYPE { get; set; }
        public string STARTDATE { get; set; }
        public string ENDDATE { get; set; }
        public string VALUE { get; set; }
        public string BU { get; set; }
        public string HIGH_ORG { get; set; }
        public string MID_ORG { get; set; }
        public string TEAM { get; set; }
        public string WORKDER_NUMBER { get; set; }
        public string DIVISION_SUB_NAME { get; set; }
        public string COST_CENTER_DESC { get; set; }
        public string JOB_TITLE { get; set; }
        public string EMPLOYEE_TYPE { get; set; }
        public string EMPLOYEE_STATUS_DESC { get; set; }
        public string CITY { get; set; }
        public string EMPLOYEE_EMAIL_ADDRESS { get; set; }
        public string MANAGER_FULL_NAME { get; set; }
        public string NETWORK_ID { get; set; }
        public string SUPERVISOR_EMAIL_ADDRESS { get; set; }
        public string CAL_YEAR { get; set; }
        public string CAL_MONTH { get; set; }
        public string CAL_Y_FISCAL_M { get; set; }
        public string CAL_MONTH_NO { get; set; }
        public string UPDATE_DT { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
    }
}
