//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProformaLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFL_MDT_FISCAL_DAYS
    {
        public int SYSID { get; set; }
        public string DAY { get; set; }
        public string FISCAL_YEAR { get; set; }
        public string FISCAL_QTR { get; set; }
        public string FISCAL_MONTH { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
    }
}
