//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProformaLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFL_MDT_SKILLS
    {
        public int SYSID { get; set; }
        public string BUSINESS { get; set; }
        public string BU { get; set; }
        public string HIGH_ORG { get; set; }
        public string MID_ORG { get; set; }
        public string TEAM { get; set; }
        public string SKILL_NAME { get; set; }
        public Nullable<System.DateTime> CREATEDON { get; set; }
    }
}
