//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProformaLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMaster
    {
        public int ID { get; set; }
        public string PROJECTNAME { get; set; }
        public string PROJECTNUMBER { get; set; }
        public string PROJECTCATEGORY { get; set; }
        public string PMNETWORKID { get; set; }
        public string PMNAME { get; set; }
        public string CATEGORYGROUP { get; set; }
        public string PARENTCHILD { get; set; }
        public string WBSELEMENT { get; set; }
        public string CAPITALEXPENDITUREWBS { get; set; }
        public string GPSPROJECTNUMBER { get; set; }
        public string PROGRAM { get; set; }
        public string BUSINESSUNIT { get; set; }
        public string PERIODBURDENEXPENSE { get; set; }
        public string SETTLEMENTCOSTCENTER { get; set; }
        public string SETTLEMENTCOSTCENTERNAME { get; set; }
        public string SETTLEMNETSUMMARY { get; set; }
        public string ENDINGBUSINESSUNIT { get; set; }
        public string FUNDINGSOURCE { get; set; }
        public string SCORECARD { get; set; }
        public string INPLAN { get; set; }
        public string FUNCTION { get; set; }
        public string CAPITALGRPTYPE { get; set; }
        public string FUNDED { get; set; }
        public Nullable<double> PERCENTFUNDED { get; set; }
        public Nullable<double> PCTPROPABILTYFUNDED { get; set; }
    }
}
