//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProformaLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource_TempData
    {
        public int Sysid { get; set; }
        public string ProjectID { get; set; }
        public string WBSNumber { get; set; }
        public string Business { get; set; }
        public string BusinessUnit { get; set; }
        public string HighOrg { get; set; }
        public string MidOrg { get; set; }
        public string Team { get; set; }
        public string RequiredSkills { get; set; }
        public string FinYear { get; set; }
        public string MAY { get; set; }
        public string JUN { get; set; }
        public string JUL { get; set; }
        public string AUG { get; set; }
        public string SEP { get; set; }
        public string OCT { get; set; }
        public string NOV { get; set; }
        public string DEC { get; set; }
        public string JAN { get; set; }
        public string FEB { get; set; }
        public string MAR { get; set; }
        public string APR { get; set; }
        public string Comments { get; set; }
    }
}
