//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProformaLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PDW_CJI3
    {
        public int Sysid { get; set; }
        public string CJI3_FinYear { get; set; }
        public string CJI3_Month { get; set; }
        public string CJI3_WBSNumber { get; set; }
        public string PWD_BusinessUnit { get; set; }
        public string PWD_HighOrg { get; set; }
        public string PWD_MidOrg { get; set; }
        public string PWD_Team { get; set; }
        public string PWD_ResourceName { get; set; }
        public Nullable<decimal> CJI3_TimeSpentInProject { get; set; }
        public Nullable<decimal> CJI3_Amount { get; set; }
    }
}
